### ISSUE TITLE
cant import pywt WaveletPacket

### ISSUE THREAD

**Issue by mamonu** [actondev/wavelet-denoiser#1]
Hi, 
Thanks for sharing your work. I'm trying to use this on an audio pipeline.

Trying to use the denoiser-argument.py script. Have installed all reqs. 

when i do something like:
python waveletdenoiser/denoiser-argument.py -i out16km.wav -o outdenoised.wav

i get 

` AttributeError: module 'pywt' has no attribute 'WaveletPacket'`

any suggestions? Does  pywt work properly on your system?
perhaps if you have an earlier version than 1.0.6  which is the current one,
this should be put to the requirements.txt

ps. using anaconda distribution of py3.6

**Comment by actondev** [comment]
hello there,
will try to upload some recent changes - which are not pushed - and also put an example usage in the wiki using `docker` - for making sure that the given example command works in whatever system (given that docker is installed of course)

will also tell you which python & pywt version exactly I have installed

don't remember stumbling upon this problem however.. but then again never used the anaconda distribution either

and thanks for reporting the issue :)

**Comment by actondev** [comment]
in the meantime you can try http://192.81.220.187:8080/ - which internally uses this very wavelet denoiser - and tell me if the results you get are satisfying..ish :P

**Comment by actondev** [comment]
@mamonu `pip3 freeze` gives me `PyWavelets==0.5.2`
and here https://github.com/PyWavelets/pywt/releases `0.5.2` is the latest..

**Comment by mamonu** [comment]
so un-installed everything related to wavelets on my python distribution. then reinstalled pyWavelets 0.5.2Then it works! 

It seems there are a lot of ways pywt can be in a python system. by uninstalling and installing again however this works.

Thanks for the support.
