### ISSUE TITLE
Denoising this reverb filter

### ISSUE THREAD

**Issue by gogo9th** [actondev/wavelet-denoiser#4]
Hi,

I am a software research trying to denoise the following reverb filter file which was recorded from an MP3 player by playing an impulse wave with a reverb effect. 

https://drive.google.com/file/d/1zOX5rUp4C-GO0PpZNcrKJ07a5B_ba5tO/view?usp=sharing 

[
<img width="1263" alt="제목 없음" src="https://user-images.githubusercontent.com/8513552/95007707-b2fb6380-064d-11eb-92cc-e2f9ac79a152.png">
[myfilter.zip](https://github.com/actonDev/wavelet-denoiser/files/5322702/myfilter.zip)

](url)

I convoluted this filter with my target music file to create a music file that has a reverb effect. However, As you can see from the above filter, this reverb filter has some noise (generated while physically recording the filter by using a cable), which I think is the cause of the faint resulting sound compared to a reverb music directly played by the MP3 player. 

So my goal is to denoise the above filter. But I am not sure what will be the best configuration setup for your software to denoise this filter... Which one-line command do you think would do the best job for this? I would really appreciate your help.

**Comment by actondev** [comment]
Hi,

You can try the `-t` parameter, which specifies the time range of where there is only noise. If indeed in that window (that you marked with red) you only hear the noise then it might work.

As seen in the readme, an example usage is `-t 0.1-0.5` if this noisy range is from 0.1s to 0.5s.

As for the rest of the settings, the defaults should be ok for sampling rate of 44100.

Let me know how it works out :)

**Comment by gogo9th** [comment]
I think this works out well. Thank you very much for your kind instruction!
